---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
    - hugo --printMemoryUsage --printUnusedTemplates --templateMetrics --minify

  - name: deploy
    commands:
    - rsync -avc --delete public/ /var/www/homepage