version: 18
jobs:
- name: CI
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build
    runInContainer: true
    image: alpine:3.17
    interpreter: !DefaultInterpreter
      commands:
      - echo "==> (1/4) Set Repositories Mirror"
      - sed -i 's/dl-cdn.alpinelinux.org/mirrors.bfsu.edu.cn/g' /etc/apk/repositories
      - echo "==> (2/4) Install hugo, tzdata, git"
      - apk update && apk add hugo tzdata git
      - echo "==> (3/4) Build Site"
      - hugo --printMemoryUsage --printUnusedTemplates --templateMetrics --minify
      - echo "==> (3/4) Calculate Site Size"
      - du -sh public/
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: deploy
    runInContainer: true
    image: alpine:3.17
    interpreter: !DefaultInterpreter
      commands:
      - echo "==> (1/4) Set Repositories Mirror"
      - sed -i 's/dl-cdn.alpinelinux.org/mirrors.bfsu.edu.cn/g' /etc/apk/repositories
      - echo "==> (2/4) Install openssh"
      - apk update && apk add openssh
      - echo "==> (3/4) Import Key"
      - echo "@secret:SSH_KEY@" | tee /tmp/id_ed25519
      - chmod 0600 /tmp/id_ed25519
      - echo "==> (4/4) Deploy"
      - ssh -p 2022 -i /tmp/id_ed25519 -o "StrictHostKeyChecking=no" "services@@10.1.0.50"
        "rm -r /home/sites/homepage"
      - scp -P 2022 -i /tmp/id_ed25519 -o "StrictHostKeyChecking=no" -r "public" "services@@10.1.0.50:/home/sites/homepage"
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
