baseURL: "https://negoces.top/"
title: "NEGOCES"
timeZone: "Asia/Shanghai"
languageCode: "zh-CN"
enableGitInfo: true
#enableInlineShortcodes: true
enableRobotsTXT: true
hasCJKLanguage: true
copyright: Copyright © 2020 - 2022 negoces

paginate: 0
summaryLength: 70

permalinks:
  posts: /posts/:slug/

params:
  repoName: git.negoces.top/negoces/homepage
  avatar: /img/avatar.png
  selfTags:
    - Student
    - Arch Linux User
    - Developers
  msg: 人最重要的特点是会思考，写博客的初衷是保存思维的电子快照。 当然各种文档工具亦或是简单的文本编辑器也能随时记录点滴，选择建个人网站无非是想满足技术爱好者的偏执。
  social:
    - name: GitHub
      url: https://github.com/negoces/
      icon: fa-brands fa-github
    - name: E-Mail
      url: "mailto:nego@negoces.top"
      icon: fa-solid fa-envelope
  menu:
    - name: 主页
      url: /
    - name: 文章
      url: /posts/

markup:
  # 语法高亮列表：https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    style: monokai
    tabWidth: 4
